# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chartTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='coinsMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10, null=True)),
                ('coinName', models.CharField(max_length=30, null=True, unique=True)),
                ('circSupply', models.FloatField(null=True)),
                ('marketCap', models.FloatField(null=True)),
                ('percentChange1h', models.FloatField(null=True)),
                ('percentChange24h', models.FloatField(null=True)),
                ('percentChange7d', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='loser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pairTickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinFrom', models.CharField(max_length=5, null=True)),
                ('coinTo', models.CharField(max_length=5, null=True)),
                ('low24hr', models.FloatField(null=True)),
                ('idPol', models.IntegerField(null=True)),
                ('percentChange', models.FloatField(null=True)),
                ('isFrozen', models.IntegerField(null=True)),
                ('quoteVolume', models.FloatField(null=True)),
                ('last', models.FloatField(null=True)),
                ('baseVolume', models.FloatField(null=True)),
                ('high24hr', models.FloatField(null=True)),
                ('lowestAsk', models.FloatField(null=True)),
                ('highestBid', models.FloatField(null=True)),
                ('exchange', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='top10MarketCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=6, null=True)),
                ('marketCap', models.FloatField(null=True)),
            ],
        ),
    ]
