# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsmain',
            name='coinId',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coinsmain',
            name='coinName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
