# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170716_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsmain',
            name='coinId',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
