# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170716_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='top10marketcap',
            name='percentChange24h',
            field=models.FloatField(null=True),
        ),
    ]
